### ISSUE TITLE
extract labelfields

### ISSUE THREAD

**Issue by rijobro** [casperdcl/brainweb#2]
is there an easy way to extract labelfields for the different VOIs (white matter, grey matter, skin, etc.)? End goal is to create a 4D `.nii` with a 3D image per VOI. Background would also be nice. The values can be binary or probabilistic, we don't mind (as long as sum =1). 

Our initial thought was to use `petNoise=0, petSigma=0` and then do value-based labelfields, but I'm not sure what happens when you have a mixture of two VOIs in the same voxel.

**Comment by casperdcl** [comment]
Sorry somehow missed the notification about this! Will post a snippet in <24h
