### ISSUE TITLE
get_mMR_from_file ignore parameters?

### ISSUE THREAD

**Issue by KrisThielemans** [casperdcl/brainweb#3]
I believe these are wrong
https://github.com/casperdcl/brainweb/blob/202eb4024591280d66dbbe853f29932909a6c6ab/brainweb/utils.py#L259-L260
as they overwrite any arguments specified to the function, but should be
```python
petNoise=petNoise, t1Noise=t1Noise, t2Noise=t2Noise, 
 petSigma=petSigma, t1Sigma=t1Sigma, t2Sigma=t2Sigma, 
```

**Comment by casperdcl** [comment]
Sorry somehow missed the notification about this! Will fix in <24h
