### ISSUE TITLE
allow specifying different resolution

### ISSUE THREAD

**Issue by KrisThielemans** [casperdcl/brainweb#4]
`toPetMmR` has an an `outres` parameter
https://github.com/casperdcl/brainweb/blob/202eb4024591280d66dbbe853f29932909a6c6ab/brainweb/utils.py#L398-L399

It would be nice to be able to pass this to the higher level `get_mmr` and `get_mmr_fromfile` as well, such that we can get images at different voxel-size out.

It would be even better to be able to specify arbitrary voxel-size/shape, but that seems to only be possible by modifying the `Res`/`Shape` classes, which seems to require major surgery, or possibly doing a `setattr(Res, mMR, ...)` and same for `Shape`

**Comment by casperdcl** [comment]
Sorry somehow missed the notification about this! Will fix in <24h
